# Generated by Django 2.2.17 on 2020-11-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placecall', models.ManyToManyField(related_name='phone_placecall', to='call.Call')),
            ],
        ),
    ]
